### ISSUE TITLE
LZ4BlockInputStream lz4-java-1.1.1 needs to read fully

### ISSUE THREAD

**Issue by gabeki** [lz4/lz4-java#13]
java.io.IOException: Stream is corrupted
    at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:159)
    at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:123)
    at org.apache.commons.io.IOUtils.read(IOUtils.java:2454)
    at org.apache.commons.io.IOUtils.read(IOUtils.java:2476)

I think this line 

```
in.read(compressedBuffer, 0, HEADER_LENGTH);
```

needs to read fully.

**Comment by Tagar** [comment]
Might be the same problem as described https://github.com/apache/spark/pull/15632 ?
https://issues.apache.org/jira/browse/SPARK-18105
